services:
  db:
    image: mysql:8.0
    container_name: cookinup_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookin_up
      MYSQL_USER: cookinup_user
      MYSQL_PASSWORD: 1234
    ports: ["127.0.0.1:3306:3306"]
    volumes:
      - ./volumes-mysql:/var/lib/mysql
      - ./cookin_up.sql:/docker-entrypoint-initdb.d/cookin_up.sql:ro
    networks:
      - proxy

  wordpress:
    build: .
    image: cookinup_wordpress:6.8.1-php8.1-apache
    container_name: cookinup_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: cookinup_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: cookin_up
    volumes:
      - ./volumes-wp:/var/www/html
    networks:
      - proxy
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`www.cookinup.com.br`)"
      - "traefik.http.routers.wordpress.entrypoints=web,websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cookinup_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.cookinup.com.br`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web,websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=seuemail@cookinup.com.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
